<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Unclaimed Found Items - {{ $organization->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #059669; padding-bottom: 15px; }
        .org-name { font-size: 20px; font-weight: bold; color: #059669; margin-bottom: 5px; }
        .report-title { font-size: 16px; font-weight: bold; color: #dc2626; margin-bottom: 10px; }
        .contact-info { background: #f0fdf4; padding: 10px; margin-bottom: 20px; border-left: 3px solid #059669; }
        .item { border: 1px solid #ddd; margin-bottom: 15px; padding: 10px; page-break-inside: avoid; }
        .item-header { display: flex; margin-bottom: 8px; }
        .item-image { width: 50px; height: 50px; object-fit: cover; margin-right: 10px; border: 1px solid #ccc; }
        .no-image { width: 50px; height: 50px; background: #f0f0f0; border: 1px solid #ccc; display: flex; align-items: center; justify-content: center; font-size: 8px; margin-right: 10px; }
        .item-title { font-weight: bold; font-size: 14px; margin: 0; }
        .item-details { font-size: 10px; }
        .item-details p { margin: 2px 0; }
        .label { font-weight: bold; }
        .footer { margin-top: 30px; text-align: center; font-size: 9px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="org-name">{{ $organization->name }}</div>
        <div class="report-title">UNCLAIMED FOUND ITEMS</div>
        <div>Generated on {{ now()->format('F d, Y \a\t g:i A') }}</div>
    </div>

    <div class="contact-info">
        <strong>Contact Information:</strong><br>
        Organization: {{ $organization->name }}<br>
        @if($organization->contact_email) Email: {{ $organization->contact_email }}<br> @endif
        @if($organization->contact_phone) Phone: {{ $organization->contact_phone }}<br> @endif
        @if($organization->address) Address: {{ $organization->address }}<br> @endif
        Total Items: {{ $foundItems->count() }}
    </div>

    @if($foundItems->count() > 0)
        @foreach($foundItems as $item)
            <div class="item">
                <div class="item-header">
                    @if(isset($item->image_base64) && $item->image_base64)
                        <img src="{{ $item->image_base64 }}" alt="{{ $item->title }}" class="item-image">
                    @else
                        <div class="no-image">No Image</div>
                    @endif
                    <div>
                        <h3 class="item-title">{{ $item->title }}</h3>
                    </div>
                </div>
                
                <div class="item-details">
                    <p><span class="label">Category:</span> {{ $item->category ?? 'N/A' }}</p>
                    <p><span class="label">Location Found:</span> {{ $item->location ?? 'N/A' }}</p>
                    <p><span class="label">Date Found:</span> {{ $item->date_found ? $item->date_found->format('M d, Y') : 'N/A' }}</p>
                    <p><span class="label">Found By:</span> {{ $item->user?->first_name }} {{ $item->user?->last_name }}</p>
                    <p><span class="label">Reported:</span> {{ $item->created_at->format('M d, Y') }}</p>
                </div>
            </div>
        @endforeach
    @else
        <div style="text-align: center; color: #666; font-style: italic; margin: 40px 0;">
            No unclaimed found items found.
        </div>
    @endif

    <div class="footer">
        Generated by Lost & Found Management System<br>
        If you recognize any items, contact the organization directly
    </div>
</body>
</html>
